repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 89c421dff2e1026ba12cdb9ebd731f4a83aa8021  # v0.8.6
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: bbc3dc1f890007061f18f17e2334f216ea9e5df7  # v1.14.1
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic==2.10.6
          - pyyaml==6.0.2
        args: ["--ignore-missing-imports"]
        pass_filenames: false
        entry: mypy Asgard/

  - repo: https://github.com/Yelp/detect-secrets
    rev: 01886c8a910c64595c47f186ca1ffc0b77fa5458  # v1.5.0
    hooks:
      - id: detect-secrets
