"""
Python Generator Helpers.

Code generation helper functions for PythonGeneratorService.
"""

from typing import Any

from Asgard.Forseti.CodeGen.models.codegen_models import (
    CodeGenConfig,
    GeneratedFile,
    HttpClientType,
    MethodDefinition,
    PropertyDefinition,
    TargetLanguage,
    TypeDefinition,
)
from Asgard.Forseti.CodeGen.services._codegen_safety import (
    escape_docstring,
    python_literal,
    python_path_lines,
    sanitize_identifier,
    string_literal,
)


def generate_property(prop_def: PropertyDefinition, include_documentation: bool) -> str:
    """Generate a single property definition."""
    type_str = prop_def.type_name
    if not prop_def.required:
        type_str = f"Optional[{type_str}]"
    if prop_def.nullable and prop_def.required:
        type_str = f"{prop_def.type_name} | None"
    field_args: list[str] = []
    if prop_def.default_value is not None:
        field_args.append(f"default={python_literal(prop_def.default_value)}")
    elif not prop_def.required:
        field_args.append("default=None")
    if prop_def.description and include_documentation:
        field_args.append(f"description={string_literal(prop_def.description)}")
    name = sanitize_identifier(prop_def.name)
    if field_args:
        return f"{name}: {type_str} = Field({', '.join(field_args)})"
    return f"{name}: {type_str}"


def generate_type(type_def: TypeDefinition, include_documentation: bool) -> list[str]:
    """Generate Python code for a type definition."""
    lines: list[str] = []
    type_name = sanitize_identifier(type_def.name)
    if type_def.is_enum:
        lines.append(f"class {type_name}(str, Enum):")
        if type_def.description and include_documentation:
            lines.append(f'    """{escape_docstring(type_def.description)}"""')
            lines.append("")
        for value in type_def.enum_values:
            if isinstance(value, str):
                enum_name = sanitize_identifier(
                    value.upper().replace("-", "_").replace(" ", "_"),
                    fallback="VALUE",
                )
                lines.append(f"    {enum_name} = {string_literal(value)}")
            else:
                enum_name = sanitize_identifier(f"VALUE_{value}", fallback="VALUE")
                lines.append(f"    {enum_name} = {python_literal(value)}")
    else:
        lines.append(f"class {type_name}(BaseModel):")
        if type_def.description and include_documentation:
            lines.append(f'    """{escape_docstring(type_def.description)}"""')
            lines.append("")
        if not type_def.properties:
            lines.append("    pass")
        else:
            for prop_name, prop_def in type_def.properties.items():
                prop_code = generate_property(prop_def, include_documentation)
                lines.append(f"    {prop_code}")
    return lines


def generate_models_file(types: dict[str, TypeDefinition], spec_data: dict[str, Any], config: CodeGenConfig) -> GeneratedFile:
    """Generate the models.py file."""
    lines: list[str] = []
    info = spec_data.get("info", {})
    title = escape_docstring(str(info.get("title", "API")))
    lines.append('"""')
    lines.append(f"{title} - Model Definitions")
    lines.append("")
    lines.append("Generated by Forseti CodeGen")
    if info.get("version"):
        lines.append(f"API Version: {escape_docstring(str(info.get('version')))}")
    lines.append('"""')
    lines.append("")
    lines.append("from datetime import date, datetime")
    lines.append("from enum import Enum")
    lines.append("from typing import Any, Optional")
    lines.append("")
    lines.append("from pydantic import BaseModel, Field")
    lines.append("")
    lines.append("")
    for type_name, type_def in types.items():
        type_code = generate_type(type_def, config.include_documentation)
        lines.extend(type_code)
        lines.append("")
        lines.append("")
    content = "\n".join(lines)
    return GeneratedFile(path="models.py", content=content, language=TargetLanguage.PYTHON, file_type="models", line_count=len(lines))


def generate_request_method(config: CodeGenConfig) -> list[str]:
    """Generate the private request method."""
    lines: list[str] = []
    is_async = config.use_async
    async_kw = "async " if is_async else ""
    if is_async and config.http_client == HttpClientType.HTTPX:
        lines.append(f"    {async_kw}def _request(self, method: str, path: str, params: Optional[dict[str, Any]] = None, json_data: Optional[Any] = None) -> Any:")
        lines.append('        """Make an HTTP request."""')
        lines.append('        url = f"{self.base_url}{path}"')
        lines.append("")
        lines.append("        if self._client:")
        lines.append("            response = await self._client.request(method, url, params=params, json=json_data, headers=self.headers)")
        lines.append("        else:")
        lines.append("            async with httpx.AsyncClient() as client:")
        lines.append("                response = await client.request(method, url, params=params, json=json_data, headers=self.headers)")
    else:
        lines.append(f"    def _request(self, method: str, path: str, params: Optional[dict[str, Any]] = None, json_data: Optional[Any] = None) -> Any:")
        lines.append('        """Make an HTTP request."""')
        lines.append('        url = f"{self.base_url}{path}"')
        lines.append("")
        lines.append("        response = requests.request(method, url, params=params, json=json_data, headers=self.headers)")
    lines.extend([
        "",
        "        if response.status_code >= 400:",
        '            raise ApiError(f"Request failed: {response.status_code}", response.status_code, response.text)',
        "",
        "        if response.status_code == 204:",
        "            return None",
        "",
        "        return response.json()",
    ])
    return lines


def generate_api_method(method: MethodDefinition, config: CodeGenConfig) -> list[str]:
    """Generate a single API method."""
    lines: list[str] = []
    is_async = config.use_async
    async_kw = "async " if is_async else ""
    await_kw = "await " if is_async else ""
    method_name = sanitize_identifier(method.name)
    lines.append(f"    {async_kw}def {method_name}(")
    lines.append("        self,")
    for param in method.parameters:
        optional = " = None" if not param.required else ""
        ident = sanitize_identifier(param.name)
        lines.append(f"        {ident}: {param.type_name}{optional},")
    if method.request_body_type:
        lines.append(f"        data: {method.request_body_type},")
    response_type = method.response_type or "Any"
    lines.append(f"    ) -> {response_type}:")
    if config.include_documentation and method.description:
        lines.append(f'        """{escape_docstring(method.description)}')
        if method.deprecated:
            lines.extend(["", "        .. deprecated::"])
        lines.append('        """')
    query_params = [p for p in method.parameters if p.location == "query"]
    lines.extend(python_path_lines(method.path, method.parameters))
    if query_params:
        lines.append("        params = {")
        for param in query_params:
            ident = sanitize_identifier(param.name)
            lines.append(f"            {string_literal(param.name)}: {ident},")
        lines.append("        }")
        lines.append("        params = {k: v for k, v in params.items() if v is not None}")
    else:
        lines.append("        params = None")
    json_arg = ", json_data=data.model_dump()" if method.request_body_type else ""
    lines.append(
        f"        result = {await_kw}self._request({string_literal(method.http_method)}, path, params=params{json_arg})"
    )
    if response_type != "Any" and response_type not in ["str", "int", "float", "bool", "None"]:
        base_type = response_type.split("[")[0]
        if response_type.startswith("list["):
            lines.append(f"        return [{base_type.rstrip(']')}(**item) for item in result]")
        else:
            lines.append(f"        return {base_type}(**result) if result else None")
    else:
        lines.append("        return result")
    return lines


def get_type_imports(methods: list[MethodDefinition], types: dict[str, TypeDefinition]) -> set[str]:
    """Get the set of types that need to be imported."""
    imports: set[str] = set()
    for method in methods:
        if method.request_body_type:
            base_type = method.request_body_type.split("[")[0]
            if base_type in types:
                imports.add(base_type)
        if method.response_type:
            base_type = method.response_type.split("[")[0]
            if base_type in types:
                imports.add(base_type)
    return imports


def generate_client_file(methods: list[MethodDefinition], types: dict[str, TypeDefinition], spec_data: dict[str, Any], config: CodeGenConfig) -> GeneratedFile:
    """Generate the client.py file."""
    lines: list[str] = []
    info = spec_data.get("info", {})
    is_async = config.use_async
    title = escape_docstring(str(info.get("title", "API")))
    lines.extend(['"""', f"{title} - API Client", "", "Generated by Forseti CodeGen", '"""', ""])
    lines.append("from typing import Any, Optional")
    lines.append("")
    if is_async and config.http_client == HttpClientType.HTTPX:
        lines.append("import httpx")
    elif is_async and config.http_client == HttpClientType.AIOHTTP:
        lines.append("import aiohttp")
    else:
        lines.append("import requests")
    lines.append("")
    type_imports = get_type_imports(methods, types)
    if type_imports:
        lines.append(f"from .models import {', '.join(sorted(type_imports))}")
        lines.append("")
    lines.append("")
    lines.extend([
        "class ApiError(Exception):",
        '    """API error with status code and response."""',
        "",
        "    def __init__(self, message: str, status_code: int, response: Any = None):",
        "        super().__init__(message)",
        "        self.status_code = status_code",
        "        self.response = response",
        "",
        "",
        "class ApiClient:",
        f'    """{escape_docstring(str(info.get("title", "API")))} client."""',
        "",
        "    def __init__(self, base_url: str, headers: Optional[dict[str, str]] = None,",
    ])
    if is_async and config.http_client == HttpClientType.HTTPX:
        lines.append("        client: Optional[httpx.AsyncClient] = None,")
    lines.extend([
        "    ):",
        '        self.base_url = base_url.rstrip("/")',
        '        self.headers = {"Content-Type": "application/json", **(headers or {})}',
    ])
    if is_async and config.http_client == HttpClientType.HTTPX:
        lines.append("        self._client = client")
    lines.append("")
    lines.extend(generate_request_method(config))
    lines.append("")
    for method in methods:
        lines.extend(generate_api_method(method, config))
        lines.append("")
    content = "\n".join(lines)
    return GeneratedFile(path="client.py", content=content, language=TargetLanguage.PYTHON, file_type="client", line_count=len(lines))
